name: funify
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  gradient_borders: ^1.0.1
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  http: ^1.3.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  path: ^1.9.0
  just_audio: ^0.10.0
  audio_session: ^0.2.1
  flutter_cache_manager: ^3.3.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.0
  table_calendar: ^3.0.9
  provider: ^6.1.1
  sqflite: ^2.3.0
  flutter_quill: ^9.0.0
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.22+1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/bg_login_background.png
    - assets/images/bg_logo_logo.png
    - assets/images/consclose_nor.png
    - assets/images/conslove_nor.png
    - assets/images/conschat_nor.png
    - assets/images/tab_nor/
    - assets/images/tab_pre/
    - assets/json/
    - assets/json/modern.json
    - assets/images/userInfo/
    - assets/images/userInfo/user_1/
    - assets/images/userInfo/user_1/user_1.jpg
    - assets/images/userInfo/user_1/photo_1.jpg
    - assets/images/userInfo/user_1/photo_2.jpg
    - assets/images/userInfo/user_2/
    - assets/images/userInfo/user_2/user_2.jpg
    - assets/images/userInfo/user_2/photo_1.jpg
    - assets/images/userInfo/user_2/photo_2.jpg
    - assets/images/userInfo/user_3/
    - assets/images/userInfo/user_3/user_3.jpg
    - assets/images/userInfo/user_3/photo_1.jpg
    - assets/images/userInfo/user_3/photo_2.jpg
    - assets/images/userInfo/user_4/
    - assets/images/userInfo/user_4/user_4.jpg
    - assets/images/userInfo/user_4/photo_1.jpg
    - assets/images/userInfo/user_4/photo_2.jpg
    - assets/images/userInfo/user_5/
    - assets/images/userInfo/user_5/user_5.jpg
    - assets/images/userInfo/user_5/photo_1.jpg
    - assets/images/userInfo/user_5/photo_2.jpg
    - assets/images/userInfo/user_6/
    - assets/images/userInfo/user_6/user_6.jpg
    - assets/images/userInfo/user_6/photo_1.jpg
    - assets/images/userInfo/user_6/photo_2.jpg
    - assets/images/userInfo/user_7/
    - assets/images/userInfo/user_7/user_7.jpg
    - assets/images/userInfo/user_7/photo_1.jpg
    - assets/images/userInfo/user_7/photo_2.jpg
    - assets/images/userInfo/user_8/
    - assets/images/userInfo/user_8/user_8.jpg
    - assets/images/userInfo/user_8/photo_1.jpg
    - assets/images/userInfo/user_8/photo_2.jpg
    - assets/images/userInfo/user_9/
    - assets/images/userInfo/user_9/user_9.jpg
    - assets/images/userInfo/user_9/photo_1.jpg
    - assets/images/userInfo/user_9/photo_2.jpg
    - assets/images/userInfo/user_10/
    - assets/images/userInfo/user_10/user_10.jpg
    - assets/images/userInfo/user_10/photo_1.jpg
    - assets/images/userInfo/user_10/photo_2.jpg
    - assets/images/userInfo/user_11/
    - assets/images/userInfo/user_11/user_11.jpg
    - assets/images/userInfo/user_11/photo_1.jpg
    - assets/images/userInfo/user_11/photo_2.jpg
    - assets/images/userInfo/user_12/
    - assets/images/userInfo/user_12/user_12.jpg
    - assets/images/userInfo/user_12/photo_1.jpg
    - assets/images/userInfo/user_12/photo_2.jpg
    - assets/images/userInfo/user_13/
    - assets/images/userInfo/user_13/user_13.jpg
    - assets/images/userInfo/user_13/photo_1.jpg
    - assets/images/userInfo/user_13/photo_2.jpg
    - assets/images/userInfo/user_14/
    - assets/images/userInfo/user_14/user_14.jpg
    - assets/images/userInfo/user_14/photo_1.jpg
    - assets/images/userInfo/user_14/photo_2.jpg
    - assets/images/userInfo/user_15/
    - assets/images/userInfo/user_15/user_15.jpg
    - assets/images/userInfo/user_15/photo_1.jpg
    - assets/images/userInfo/user_15/photo_2.jpg
    - assets/images/userInfo/user_16/
    - assets/images/userInfo/user_16/user_16.jpg
    - assets/images/userInfo/user_16/photo_1.jpg
    - assets/images/userInfo/user_16/photo_2.jpg
    - assets/images/userInfo/user_17/
    - assets/images/userInfo/user_17/user_17.jpg
    - assets/images/userInfo/user_17/photo_1.jpg
    - assets/images/userInfo/user_17/photo_2.jpg
    - assets/images/userInfo/user_18/
    - assets/images/userInfo/user_18/user_18.jpg
    - assets/images/userInfo/user_18/photo_1.jpg
    - assets/images/userInfo/user_18/photo_2.jpg
    - assets/images/userInfo/user_19/
    - assets/images/userInfo/user_19/user_19.jpg
    - assets/images/userInfo/user_19/photo_1.jpg
    - assets/images/userInfo/user_19/photo_2.jpg
    - assets/images/userInfo/user_20/
    - assets/images/userInfo/user_20/user_20.jpg
    - assets/images/userInfo/user_20/photo_1.jpg
    - assets/images/userInfo/user_20/photo_2.jpg
    - assets/images/userInfo/user_21/
    - assets/images/userInfo/user_21/user_21.jpg
    - assets/images/userInfo/user_21/photo_1.jpg
    - assets/images/userInfo/user_21/photo_2.jpg
    - assets/images/userInfo/user_22/
    - assets/images/userInfo/user_22/user_22.jpg
    - assets/images/userInfo/user_22/photo_1.jpg
    - assets/images/userInfo/user_22/photo_2.jpg
    - assets/images/userInfo/user_23/
    - assets/images/userInfo/user_23/user_23.jpg
    - assets/images/userInfo/user_23/photo_1.jpg
    - assets/images/userInfo/user_23/photo_2.jpg
    - assets/images/userInfo/user_24/
    - assets/images/userInfo/user_24/user_24.jpg
    - assets/images/userInfo/user_24/photo_1.jpg
    - assets/images/userInfo/user_24/photo_2.jpg
    - assets/images/userInfo/user_25/
    - assets/images/userInfo/user_25/user_25.jpg
    - assets/images/userInfo/user_25/photo_1.jpg
    - assets/images/userInfo/user_25/photo_2.jpg
    - assets/images/userInfo/user_26/
    - assets/images/userInfo/user_26/user_26.jpg
    - assets/images/userInfo/user_26/photo_1.jpg
    - assets/images/userInfo/user_26/photo_2.jpg
    - assets/images/userInfo/user_27/
    - assets/images/userInfo/user_27/user_27.jpg
    - assets/images/userInfo/user_27/photo_1.jpg
    - assets/images/userInfo/user_27/photo_2.jpg
    - assets/images/userInfo/user_28/
    - assets/images/userInfo/user_28/user_28.jpg
    - assets/images/userInfo/user_28/photo_1.jpg
    - assets/images/userInfo/user_28/photo_2.jpg
    - assets/images/userInfo/user_29/
    - assets/images/userInfo/user_29/user_29.jpg
    - assets/images/userInfo/user_29/photo_1.jpg
    - assets/images/userInfo/user_29/photo_2.jpg
    - assets/images/userInfo/user_30/
    - assets/images/userInfo/user_30/user_30.jpg
    - assets/images/userInfo/user_30/photo_1.jpg
    - assets/images/userInfo/user_30/photo_2.jpg
    - assets/music/
    - assets/music/music_1.mp3
    - assets/music/music_2.mp3
    - assets/music/music_3.mp3
    - assets/music/music_4.mp3
    - assets/music/music_5.mp3
    - assets/music/music_6.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
