name: ailly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  gradient_borders: ^1.0.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  http: ^1.3.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  path: ^1.9.1
  just_audio: ^0.10.0
  audio_session: ^0.2.1
  flutter_cache_manager: ^3.3.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.0
  table_calendar: ^3.0.9

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/bg_login_background.png
    - assets/images/bg_logo_logo.png
    - assets/images/btn_friends_close_nor.png
    - assets/images/btn_friends_love_nor.png
    - assets/images/btn_friends_chat_nor.png
    - assets/images/tab_nor/
    - assets/images/tab_pre/
    - assets/json/
    - assets/json/modern.json
    - assets/images/userInfo/
    - assets/images/userInfo/1/
    - assets/images/userInfo/1/user_1.jpg
    - assets/images/userInfo/1/photo_1.jpg
    - assets/images/userInfo/1/photo_2.jpg
    - assets/images/userInfo/2/
    - assets/images/userInfo/2/user_2.jpg
    - assets/images/userInfo/2/photo_1.jpg
    - assets/images/userInfo/2/photo_2.jpg
    - assets/images/userInfo/3/
    - assets/images/userInfo/3/user_3.jpg
    - assets/images/userInfo/3/photo_1.jpg
    - assets/images/userInfo/3/photo_2.jpg
    - assets/images/userInfo/4/
    - assets/images/userInfo/4/user_4.jpg
    - assets/images/userInfo/4/photo_1.jpg
    - assets/images/userInfo/4/photo_2.jpg
    - assets/images/userInfo/5/
    - assets/images/userInfo/5/user_5.jpg
    - assets/images/userInfo/5/photo_1.jpg
    - assets/images/userInfo/5/photo_2.jpg
    - assets/images/userInfo/6/
    - assets/images/userInfo/6/user_6.jpg
    - assets/images/userInfo/6/photo_1.jpg
    - assets/images/userInfo/6/photo_2.jpg
    - assets/images/userInfo/7/
    - assets/images/userInfo/7/user_7.jpg
    - assets/images/userInfo/7/photo_1.jpg
    - assets/images/userInfo/7/photo_2.jpg
    - assets/images/userInfo/8/
    - assets/images/userInfo/8/user_8.jpg
    - assets/images/userInfo/8/photo_1.jpg
    - assets/images/userInfo/8/photo_2.jpg
    - assets/images/userInfo/9/
    - assets/images/userInfo/9/user_9.jpg
    - assets/images/userInfo/9/photo_1.jpg
    - assets/images/userInfo/9/photo_2.jpg
    - assets/images/userInfo/10/
    - assets/images/userInfo/10/user_10.jpg
    - assets/images/userInfo/10/photo_1.jpg
    - assets/images/userInfo/10/photo_2.jpg
    - assets/images/userInfo/11/
    - assets/images/userInfo/11/user_11.jpg
    - assets/images/userInfo/11/photo_1.jpg
    - assets/images/userInfo/11/photo_2.jpg
    - assets/images/userInfo/12/
    - assets/images/userInfo/12/user_12.jpg
    - assets/images/userInfo/12/photo_1.jpg
    - assets/images/userInfo/12/photo_2.jpg
    - assets/images/userInfo/13/
    - assets/images/userInfo/13/user_13.jpg
    - assets/images/userInfo/13/photo_1.jpg
    - assets/images/userInfo/13/photo_2.jpg
    - assets/images/userInfo/14/
    - assets/images/userInfo/14/user_14.jpg
    - assets/images/userInfo/14/photo_1.jpg
    - assets/images/userInfo/14/photo_2.jpg
    - assets/images/userInfo/15/
    - assets/images/userInfo/15/user_15.jpg
    - assets/images/userInfo/15/photo_1.jpg
    - assets/images/userInfo/15/photo_2.jpg
    - assets/images/userInfo/16/
    - assets/images/userInfo/16/user_16.jpg
    - assets/images/userInfo/16/photo_1.jpg
    - assets/images/userInfo/16/photo_2.jpg
    - assets/images/userInfo/17/
    - assets/images/userInfo/17/user_17.jpg
    - assets/images/userInfo/17/photo_1.jpg
    - assets/images/userInfo/17/photo_2.jpg
    - assets/images/userInfo/18/
    - assets/images/userInfo/18/user_18.jpg
    - assets/images/userInfo/18/photo_1.jpg
    - assets/images/userInfo/18/photo_2.jpg
    - assets/images/userInfo/19/
    - assets/images/userInfo/19/user_19.jpg
    - assets/images/userInfo/19/photo_1.jpg
    - assets/images/userInfo/19/photo_2.jpg
    - assets/images/userInfo/20/
    - assets/images/userInfo/20/user_20.jpg
    - assets/images/userInfo/20/photo_1.jpg
    - assets/images/userInfo/20/photo_2.jpg
    - assets/images/userInfo/21/
    - assets/images/userInfo/21/user_21.jpg
    - assets/images/userInfo/21/photo_1.jpg
    - assets/images/userInfo/21/photo_2.jpg
    - assets/images/userInfo/22/
    - assets/images/userInfo/22/user_22.jpg
    - assets/images/userInfo/22/photo_1.jpg
    - assets/images/userInfo/22/photo_2.jpg
    - assets/images/userInfo/23/
    - assets/images/userInfo/23/user_23.jpg
    - assets/images/userInfo/23/photo_1.jpg
    - assets/images/userInfo/23/photo_2.jpg
    - assets/images/userInfo/24/
    - assets/images/userInfo/24/user_24.jpg
    - assets/images/userInfo/24/photo_1.jpg
    - assets/images/userInfo/24/photo_2.jpg
    - assets/images/userInfo/25/
    - assets/images/userInfo/25/user_25.jpg
    - assets/images/userInfo/25/photo_1.jpg
    - assets/images/userInfo/25/photo_2.jpg
    - assets/images/userInfo/26/
    - assets/images/userInfo/26/user_26.jpg
    - assets/images/userInfo/26/photo_1.jpg
    - assets/images/userInfo/26/photo_2.jpg
    - assets/images/userInfo/27/
    - assets/images/userInfo/27/user_27.jpg
    - assets/images/userInfo/27/photo_1.jpg
    - assets/images/userInfo/27/photo_2.jpg
    - assets/images/userInfo/28/
    - assets/images/userInfo/28/user_28.jpg
    - assets/images/userInfo/28/photo_1.jpg
    - assets/images/userInfo/28/photo_2.jpg
    - assets/images/userInfo/29/
    - assets/images/userInfo/29/user_29.jpg
    - assets/images/userInfo/29/photo_1.jpg
    - assets/images/userInfo/29/photo_2.jpg
    - assets/images/userInfo/30/
    - assets/images/userInfo/30/user_30.jpg
    - assets/images/userInfo/30/photo_1.jpg
    - assets/images/userInfo/30/photo_2.jpg
    - assets/music/
    - assets/music/music_1.mp3
    - assets/music/music_2.mp3
    - assets/music/music_3.mp3
    - assets/music/music_4.mp3
    - assets/music/music_5.mp3
    - assets/music/music_6.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
